### ISSUE TITLE
Improve title text extraction

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books-parser#8]
According to current code

https://github.com/EbookFoundation/free-programming-books-parser/blob/dc53b8c803f96a7a0de6afabcab6949bfbb79b5a/index.js#L92-L95

first node `children[0]` is used as resource titles without check if there are more meaningfull tokens. So the rest is stripped making sometimes difficult to do a search by title of resources.

![image](https://user-images.githubusercontent.com/3125580/190848931-db544d1f-5729-4ec0-a928-9ddc2617ec29.png)

Therefore a escape in resources title links part is needed when submitting and make a rebuild Markdown here is mandatory

### Context

See EbookFoundation/free-programming-books#7086
Related with #2 (same workarround)

**Comment by eshellman** [comment]
`first node children[0] is used as resource titles without check if there are more meaningfull tokens.`

Could you present an example from our current parsed data? Thanks

**Comment by davorpa** [comment]
> `first node children[0] is used as resource titles without check if there are more meaningfull tokens.`
> 
> Could you present an example from our current parsed data? Thanks

Not at all since https://github.com/EbookFoundation/free-programming-books/pull/7086 has been already fixed. Anyway I see you merge #11. Should I do anything more?

**Comment by eshellman** [comment]
I think we're good
